### ISSUE TITLE
Read from xdg-videos

### ISSUE THREAD

**Issue by Mars7x** [blissd/fotema#17]
Hello, I just discovered your app and I've been liking it!

I have one recommendation, as currently videos are only pulled from `xdg-pictures` I believe it would make more sense to also pull videos from `xdg-videos` since that is most likely where a user is going to store that type of content.

**Comment by blissd** [comment]
Thanks for the comment. I've wondered about having multiple library roots in Fotema, but I don't think I'm ready for that yet. Hopefully the current setup will work fine for many people. It works well for me, as I use the https://ente.io photo service to sync photos from my phone to my Linux laptop and the results in all the photos and videos from my phone ending up under my xdg-pictures directory.

I'm not sure I'd want all of my xdg-videos directory showing up in Fotema because it is full of long form videos that are better played with apps like VLC. Maybe one day having a library root like `xdg-videos/Camera` would make sense.

**Comment by Mars7x** [comment]
Yeah that makes more sense thinking about it now, I think having a library root for `xdg-videos/Camera` would be a good addition in the future.
