### ISSUE TITLE
Missing downloads for 1.15.0

### ISSUE THREAD

**Issue by mgorny** [blissd/fotema#233]
I'm sorry to bother you but is it intentional that 1.15.0 tag has no "downloads", i.e. no tarball with vendored crates like the previous versions had?

**Comment by blissd** [comment]
Yes, it is intentional. I've adopted an easier release process that I saw apps like [Fretboard](https://flathub.org/apps/dev.bragefuglseth.Fretboard) and [Keypunch](https://flathub.org/apps/dev.bragefuglseth.Keypunch) using. The new process skips the step of my manually creating a release tarball of all sources and instead just requires a git tag which I then reference in the [Flathub manifest](https://github.com/flathub/app.fotema.Fotema/blob/master/app.fotema.Fotema.json).

For now I've kept the old code for producing the release tarball and checksum file for now, which you can produce with running:

```shell
just dist
```

If you don't want to install [just](https://github.com/casey/just), then just peek in the `Justfile` for the command.

**Comment by mgorny** [comment]
Ah, ok. Well, I can handle that, just was happy that there are a few packages where I didn't have to do it xP.
